/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MainContent from "./MainContent";
import Header from "../Header/Header";

function AboutUsMain() {
  return (
    <div className="flex flex-col pb-52 bg-white max-md:pb-24">
      <Header />
      <MainContent />
    </div>
  );
}

export default AboutUsMain;
