/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AboutSection() {
  return (
    <section className="mt-20 ml-2.5 w-full max-w-[1364px] max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/e7658e5098f225e275953cc26148cd5ce9951a5248d84299f302c81986eb094b?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt="About Brandigo"
            className="object-contain grow w-full aspect-[1.44] max-md:max-w-full"
          />
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow items-start pt-8 pr-8 pb-16 pl-20 w-full bg-sky-900 max-md:px-5 max-md:max-w-full">
            <h2 className="text-6xl font-extrabold tracking-tighter leading-none text-zinc-100 max-md:text-4xl">
              About us
            </h2>
            <p className="mt-12 text-lg font-semibold leading-8 text-slate-200 max-md:mt-10 max-md:max-w-full">
              Brandigo was founded with a vision to revolutionize the way
              businesses operate and engage with their customers. Since our
              inception, we have been committed to delivering innovative
              solutions that drive growth, enhance efficiency, and foster
              lasting relationships. From humble beginnings, we have grown into
              a trusted partner for businesses across various industries,
              offering a wide range of services that include QR Management
              Solutions, Soundbox Management Solutions, Merchant Management
              Solutions, Printing Solutions, and Digital Marketing Solutions.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default AboutSection;
