/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AuthButtons() {
  return (
    <div className="flex gap-5 items-center my-auto">
      <button className="grow self-stretch my-auto text-slate-900">
        Login
      </button>
      <button className="self-stretch py-4 px-6 leading-none text-white bg-blue-500 rounded-3xl border border-blue-500 border-solid max-md:px-5">
        Sign up free →
      </button>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/fbbc90a4c2a14b911b4f564f7f2e80b8f64a5eefe36e006f8ea3dc4f28ddc7f0?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
        alt="Menu"
        className="object-contain shrink-0 self-stretch my-auto aspect-[1.5] w-[30px]"
      />
    </div>
  );
}

export default AuthButtons;
