/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/be071be76890934db1be2670ac28e6a5a8867ec5d934366995a6e1dccf507876?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
      alt="Brandigo Logo"
      className="object-contain shrink-0 self-stretch max-w-full aspect-[2.4] w-[185px]"
    />
  );
}

export default Logo;
