/**
 * This code was generated by Builder.io.
 */
import React from "react";
import AboutSection from "./AboutSection";
import TeamSection from "./TeamSection";
import ValuesSection from "./ValuesSection";
import WhoWeAreSection from "./WhoWeAreSection";
import MissionVisionSection from "./MissionVisionSection";
import WhyChooseSection from "./WhyChooseSection";

function MainContent() {
  return (
    <main className="flex flex-col pb-52 bg-white max-md:pb-24 overflow-hidden">
      <AboutSection />
      <p className="mt-36 ml-3.5 text-2xl font-semibold leading-10 text-center text-black max-md:mt-10 max-md:max-w-full">
        Our journey began with a small team of dedicated professionals who
        shared a common goal: to create a company that not only meets but
        exceeds the expectations of its clients. Over the years, we have
        expanded our expertise, embraced new technologies, and continuously
        improved our offerings to stay ahead of the curve. Today, Brandigo
        stands as a testament to our unwavering commitment to excellence and our
        passion for innovation.
      </p>
      <TeamSection />
      <p className="mt-40 ml-3.5 text-2xl font-semibold leading-10 text-center text-black max-md:mt-10 max-md:max-w-full">
        Our team dedication and expertise are the driving forces behind our
        success, enabling us to deliver cutting-edge solutions and exceptional
        service to our clients.
      </p>
      <ValuesSection />
      <div className="flex flex-col items-start self-center pb-11 mt-48 max-w-full w-[932px] max-md:mt-10">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
          alt=""
          className="object-contain w-6 aspect-square"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
          alt=""
          className="object-contain mt-24 w-6 aspect-square max-md:mt-10"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
          alt=""
          className="object-contain z-10 mt-14 w-6 aspect-square max-md:mt-10"
        />
        <div className="self-end mt-0 text-2xl font-semibold leading-10 text-black max-md:mt-0 max-md:max-w-full">
          Innovation: We are committed to continuous innovation, embracing new
          technologies and ideas to stay ahead of the competition and deliver
          the best solutions to our clients.
          <br />
          Integrity: We conduct our business with the highest level of
          integrity, ensuring honesty, transparency, and ethical practices in
          all our interactions.
          <br />
          Customer-Centricity: Our clients are at the heart of everything we do.
          We strive to understand their needs, exceed their expectations, and
          build long-lasting relationships based on trust and mutual success.
          <br />
          Excellence: We are dedicated to achieving excellence in every aspect
          of our work, from the quality of our solutions to the level of service
          we provide.
          <br />
          Collaboration: We believe in the power of collaboration, both within
          our team and with our clients. By working together, we achieve greater
          results and drive innovation.
          <br />
          Agility: In a rapidly changing world, we remain agile and adaptable,
          ready to respond to new challenges and opportunities with speed and
          efficiency.
        </div>
        <div className="flex z-10 flex-col mt-0 w-6 max-md:mt-0">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt=""
            className="object-contain w-full aspect-square"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt=""
            className="object-contain mt-14 w-full aspect-square max-md:mt-10"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt=""
            className="object-contain mt-24 w-full aspect-square max-md:mt-10"
          />
        </div>
      </div>
      <div className="flex flex-col items-start px-7 pb-20 mt-44 w-full max-md:px-5 max-md:mt-10 max-md:max-w-full">
        <WhoWeAreSection />
        <MissionVisionSection />
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
        alt=""
        className="object-contain mt-96 ml-52 w-6 aspect-square max-md:mt-10 max-md:ml-2.5"
      />
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
        alt=""
        className="object-contain mt-14 ml-52 w-6 aspect-square max-md:mt-10 max-md:ml-2.5"
      />
      <WhyChooseSection />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
        alt=""
        className="object-contain mt-0 ml-52 w-6 aspect-square max-md:mt-0 max-md:ml-2.5"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
        alt=""
        className="object-contain mt-14 ml-52 w-6 aspect-square max-md:mt-10 max-md:ml-2.5"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/26ed599666b5cb2fc3bb94141d3d44a96ecf0ba103e433d698e045a8aa730abe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
        alt=""
        className="object-contain mt-14 ml-52 w-6 aspect-square max-md:mt-10 max-md:ml-2.5"
      />
    </main>
  );
}

export default MainContent;
