/**
 * This code was generated by Builder.io.
 */
import React from "react";

function MissionVisionSection() {
  return (
    <section className="mt-64 max-md:mt-10 max-md:mr-0.5 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow items-start pt-10 pr-5 pb-28 pl-20 w-full bg-sky-900 max-md:pb-24 max-md:pl-5 max-md:mt-10 max-md:max-w-full">
            <h2 className="text-6xl font-extrabold tracking-tighter leading-none text-zinc-100 max-md:text-4xl">
              Our Mission
            </h2>
            <p className="mt-20 text-lg font-semibold leading-8 text-slate-200 max-md:mt-10 max-md:max-w-full">
              Our mission is to empower businesses by providing innovative,
              reliable, and efficient solutions that drive growth and enhance
              operational efficiency. At Brandigo, we are committed to fostering
              long-term partnerships with our clients, helping them navigate the
              complexities of today's business environment with ease.
            </p>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow items-start pt-10 pr-4 pb-28 pl-20 w-full bg-sky-900 max-md:pb-24 max-md:pl-5 max-md:mt-10 max-md:max-w-full">
            <h2 className="text-6xl font-extrabold tracking-tighter leading-none text-zinc-100 max-md:text-4xl">
              Our Vision
            </h2>
            <p className="mt-20 text-lg font-semibold leading-8 text-slate-200 max-md:mt-10 max-md:max-w-full">
              At Brandigo, our vision is to be the leading provider of
              innovative and comprehensive business solutions that drive growth
              and efficiency for our clients. We aim to revolutionize the
              industry by setting new standards in service delivery and
              technology integration, creating lasting value and success for
              businesses worldwide.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

export default MissionVisionSection;
