/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Navigation() {
  const navItems = [
    { label: "Services", hasDropdown: true },
    { label: "About Clients", hasDropdown: true },
    { label: "About Us" },
    { label: "Contact Us" },
  ];

  return (
    <nav className="flex gap-2.5 items-center text-slate-900">
      {navItems.map((item, index) => (
        <div
          key={index}
          className="flex gap-0.5 self-stretch my-auto text-center"
        >
          <div className="grow">{item.label}</div>
          {item.hasDropdown && (
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/9cbba0f718a8a380d641bb8dfd6ab1a35baf35d154200f4caa241d808c136957?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
              alt=""
              className="object-contain shrink-0 self-start mt-2.5 w-3 aspect-[1.2]"
            />
          )}
        </div>
      ))}
    </nav>
  );
}

export default Navigation;
