/**
 * This code was generated by Builder.io.
 */
import React from "react";

function TeamSection() {
  return (
    <section className="mt-24 w-full max-w-[1348px] max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow px-6 pt-16 pb-32 w-full bg-sky-900 max-md:px-5 max-md:pb-24 max-md:max-w-full">
            <h2 className="self-end mr-7 text-6xl font-extrabold tracking-tighter leading-none text-zinc-100 max-md:mr-2.5 max-md:text-4xl">
              Our Team
            </h2>
            <p className="mt-14 text-lg font-semibold leading-8 text-slate-200 max-md:mt-10 max-md:max-w-full">
              At Brandigo, our team is our greatest asset. Comprising industry
              experts, creative minds, and dedicated professionals, our team
              works tirelessly to deliver exceptional results for our clients.
              Each member brings a unique set of skills and experiences,
              contributing to a diverse and dynamic work environment that
              fosters collaboration and innovation.
            </p>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/404030420dcf13f8fceb6a7dd2c3ad40db03071cf4068d9c783602a06f356028?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt="Brandigo Team"
            className="object-contain grow w-full aspect-[1.47] max-md:max-w-full"
          />
        </div>
      </div>
    </section>
  );
}

export default TeamSection;
