/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ValuesSection() {
  return (
    <section className="mt-40 w-full max-w-[1360px] max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8c4e0d398c7b403caca864eca8fd88538c4cc2329b0b32003a5f229d7e8ed94b?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt="Our Values"
            className="object-contain grow w-full aspect-[1.52] max-md:max-w-full"
          />
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col grow items-start py-11 pr-1.5 pl-20 w-full bg-sky-900 max-md:pl-5 max-md:max-w-full">
            <h2 className="text-6xl font-extrabold tracking-tighter leading-none text-zinc-100 max-md:text-4xl">
              Our Values
            </h2>
            <ul className="mt-10 text-lg font-semibold leading-8 text-slate-200 max-md:max-w-full">
              <li>Innovation</li>
              <li>Integrity</li>
              <li>Customer-Centricity</li>
              <li>Excellence</li>
              <li>Collaboration</li>
              <li>Agility</li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}

export default ValuesSection;
