/**
 * This code was generated by Builder.io.
 */
import React from "react";

function WhoWeAreSection() {
  return (
    <section className="flex flex-col self-stretch w-full max-md:max-w-full">
      <div className="max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8c4e0d398c7b403caca864eca8fd88538c4cc2329b0b32003a5f229d7e8ed94b?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
              alt="Who We Are"
              className="object-contain grow w-full aspect-[1.52] max-md:max-w-full"
            />
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col grow items-start pt-10 pr-2 pb-28 pl-20 w-full bg-sky-900 max-md:pb-24 max-md:pl-5 max-md:max-w-full">
              <h2 className="text-6xl font-extrabold tracking-tighter leading-none text-zinc-100 max-md:text-4xl">
                Who We Are
              </h2>
              <p className="mt-10 text-lg font-semibold leading-8 text-slate-200 max-md:mt-10 max-md:max-w-full">
                Brandigo is a premier service provider specialising in
                integrated solutions that cater to the dynamic needs of modern
                businesses. Established with a vision to transform the way
                businesses operate, we leverage advanced technology and
                strategic insights to deliver unparalleled value to our clients.
                Our core services include QR Management Solutions, Soundbox
                Management Solutions, Merchant Management Solutions, Printing
                Solutions, and Digital Marketing Solutions.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

export default WhoWeAreSection;
