/**
 * This code was generated by Builder.io.
 */
import React from "react";

function WhyChooseSection() {
  const reasons = [
    "Innovative Technology: We utilize the latest technology to deliver state-of-the-art solutions that keep your business ahead of the curve.",
    "Expert Team: Our team of seasoned professionals brings a wealth of knowledge and experience to every project, ensuring exceptional results.",
    "Customer-Centric Approach: At Brandigo, we prioritize your needs, offering tailored solutions that align with your business objectives.",
    "Proven Track Record: With a portfolio of satisfied clients and successful projects, we have established ourselves as a trusted partner in the industry.",
    "Comprehensive Services: From merchant management and QR solutions to digital marketing and printing, our diverse range of services provides a holistic approach to business growth.",
  ];

  return (
    <section className="flex z-10 flex-col self-center mt-0 max-w-full font-semibold w-[890px] max-md:mt-0">
      <h2 className="self-center text-6xl leading-none text-center text-sky-900 max-md:max-w-full max-md:text-4xl">
        Why Choose Brandigo?
      </h2>
      <ul className="mt-32 text-2xl leading-10 text-black max-md:mt-10 max-md:max-w-full">
        {reasons.map((reason, index) => (
          <li key={index}>{reason}</li>
        ))}
      </ul>
    </section>
  );
}

export default WhyChooseSection;
