/**
 * This code was generated by Builder.io.
 */
import React from "react";

function NavItem({ label, hasDropdown, link }) {
  return (
    <div className="flex gap-2 ml-20 self-stretch my-auto text-center">
      <button className="grow">
        
        <a href={link}>

        {label}
        </a>
        </button>
      {hasDropdown && (
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/250ba567e5bf58ef4bf73f70036d2bc182acf8aabf757a5600aec559e6c633bd?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
          alt=""
          className="object-contain shrink-0 self-start mt-2.5 w-3 aspect-[1.2]"
        />
      )}
    </div>
  );
}

export default NavItem;
