/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Navigation() {
  const navItems = [
    { label: "Services", hasDropdown: true },
    { label: "About Clients", hasDropdown: true },
    { label: "About Us", hasDropdown: false },
    { label: "Contact Us", hasDropdown: false },
  ];

  return (
    <nav className="flex gap-2.5 items-center text-slate-900">
      {navItems.map((item, index) => (
        <div
          key={index}
          className="flex gap-0.5 self-stretch my-auto text-center"
        >
          <div className="grow">{item.label}</div>
          {item.hasDropdown && (
            <img
              loading="lazy"
              src={`http://b.io/ext_${index + 2}-`}
              className="object-contain shrink-0 self-start mt-2.5 w-3 aspect-[1.2]"
              alt=""
            />
          )}
        </div>
      ))}
    </nav>
  );
}

export default Navigation;
