/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface BlogCardProps {
  type: string;
  heading: string;
  content: string;
  imageSrc: string;
}

const BlogCard: React.FC<BlogCardProps> = ({
  type,
  heading,
  content,
  imageSrc,
}) => {
  return (
    <article className="flex overflow-hidden flex-col grow pb-14 w-full bg-white rounded-[48px] text-slate-900 max-md:mt-10">
      <div className="flex overflow-hidden relative flex-col items-start px-11 pb-28 w-full max-w-xs text-base font-extrabold leading-none whitespace-nowrap aspect-[2.177] max-md:px-5 max-md:pb-24">
        <img
          loading="lazy"
          src={imageSrc}
          alt=""
          className="object-cover absolute inset-0 size-full"
        />
        <span className="relative px-5 py-3 mb-0 bg-sky-50 rounded-[48px] max-md:mb-2.5">
          {type}
        </span>
      </div>
      <div className="flex flex-col pt-12 pr-12 pb-12 pl-12 w-80 max-w-full max-md:px-5">
        <h3 className="text-2xl font-bold leading-8">{heading}</h3>
        <p className="mt-6 text-base leading-6">{content}</p>
      </div>
    </article>
  );
};

export default BlogCard;
