/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Button = ({ children, variant }) => {
  const baseClasses =
    "self-stretch py-4 px-6 leading-none rounded-3xl border border-solid";
  const variantClasses = {
    primary: "text-white bg-blue-500 border-blue-500",
    text: "text-slate-900",
  };

  return (
    <button className={`${baseClasses} ${variantClasses[variant]}`}>
      {children}
    </button>
  );
};

export default Button;
