/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ClientLogoProps {
  name: string;
  imageSrc: string;
}

const ClientLogo: React.FC<ClientLogoProps> = ({ name, imageSrc }) => {
  return (
    <div className="flex flex-col">
      <img
        loading="lazy"
        src={imageSrc}
        alt={`${name} logo`}
        className="object-contain shrink-0 max-w-full"
      />
    </div>
  );
};

export default ClientLogo;
