/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer: React.FC = () => {
  return (
    <footer className="flex items-start self-stretch mt-52 bg-stone-500 max-md:mt-10">
      <div className="flex flex-col items-center px-5 py-10 min-w-[240px] w-[1458px] max-md:max-w-full">
        <div className="flex flex-wrap items-start max-w-full text-white w-[1418px]">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/4b768fca0062697b9af6238269c1739893571a6ea90a58da511bfda396609d36?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt="Company logo"
            className="object-contain shrink-0 aspect-[2.4] w-[219px]"
          />
          <nav className="flex flex-col px-2.5 pb-5 min-w-[240px]">
            <h2 className="text-lg font-bold leading-none">Services</h2>
            <ul className="flex flex-col mt-6 text-base">
              <li>QR Management Solutions</li>
              <li className="mt-2">Soundbox Management Solutions</li>
              <li className="mt-2">Merchant Management Solutions</li>
              <li className="mt-2">Printing Solutions</li>
              <li className="mt-2">Digital Marketing Solutions</li>
            </ul>
          </nav>
          <nav className="flex flex-col px-2.5 min-w-[240px]">
            <h2 className="text-lg font-bold leading-none">Our Clients</h2>
            <ul className="flex flex-col pr-16 pb-px mt-6 text-base max-md:pr-5">
              <li>Razorpay</li>
              <li className="mt-2">Fiserv</li>
              <li className="mt-2">Yes Bank</li>
              <li className="mt-2">Suryoday Bank</li>
              <li className="mt-2">ICICI Bank</li>
              <li className="mt-2">Utkarsh Small Finance Bank</li>
              <li className="mt-2">Shamrao Vithal Co-operative Bank</li>
              <li className="mt-2">NKGSB Co-operative Bank Ltd</li>
              <li className="mt-2">Election Commission of India</li>
            </ul>
          </nav>
          <nav className="flex flex-col px-2.5 pb-24 min-w-[240px]">
            <h2 className="text-lg font-bold leading-none">
              Why Choose Brandigo?
            </h2>
            <ul className="flex flex-col pr-14 pb-px mt-6 text-base max-md:pr-5">
              <li>Innovative Technology</li>
              <li className="mt-2">Expert Team</li>
              <li className="mt-2">Customer-Centric Approach</li>
              <li className="mt-2">Proven Track Record</li>
              <li className="mt-2">Comprehensive Services</li>
            </ul>
          </nav>
          <nav className="flex flex-col px-2.5 pb-56 max-md:pb-24">
            <h2 className="text-lg font-bold leading-none">Company</h2>
            <ul className="flex flex-col pr-32 pb-px mt-6 text-base max-md:pr-5">
              <li>About us</li>
              <li className="mt-2 text-base leading-relaxed">Our Vision</li>
              <li className="mt-2">Our Mission</li>
              <li className="mt-2">Our Clients</li>
              <li className="mt-2">Services</li>
              <li className="mt-2">Contact Us</li>
            </ul>
          </nav>
        </div>
        <div className="flex items-start pt-10 mt-24 max-w-full border-t border-gray-400 w-[875px] max-md:mt-10">
          <div className="flex gap-10 items-center min-w-[240px] w-[875px] max-md:max-w-full">
            <div className="flex flex-wrap gap-10 items-start self-stretch px-0.5 py-7 my-auto min-w-[240px] w-[875px] max-md:max-w-full">
              <div className="flex gap-6 items-start pb-0.5">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/d4b73073e4efc9e4f9889312706e623498d6d11f59907dcb755b5bfe9ab0f164?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
                  alt="Social media icon"
                  className="object-contain shrink-0 w-6 aspect-square"
                />
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/5427dfb28f70af1c011e66d42cf8f86755817b698dcf50873faf4bae0552c019?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
                  alt="Social media icon"
                  className="object-contain shrink-0 w-6 aspect-square"
                />
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/cec9155d57b95fc221a554d4ff16fd71f572653f3817ba7b2d2f6e659a6c7b6c?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
                  alt="Social media icon"
                  className="object-contain shrink-0 w-6 aspect-square"
                />
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/82b013ba5399d91bd6cdfdf82f0f82f9aa343eed33d3ff7190bb9ab01a167746?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
                  alt="Social media icon"
                  className="object-contain shrink-0 w-6 aspect-square"
                />
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/ea9c1a7cfdbe92436e5a5f20fe7e74bc381225a0556b4c557b579adf5067e302?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
                  alt="Social media icon"
                  className="object-contain shrink-0 w-6 aspect-square"
                />
              </div>
              <div className="flex flex-auto gap-4 text-base text-center text-white">
                <span className="my-auto text-base leading-relaxed">@2024</span>
                <span className="my-auto text-base leading-relaxed">
                  Brandigo
                </span>
                <a href="#" className="basis-auto">
                  Terms of Service
                </a>
                <a href="#" className="basis-auto">
                  Privacy Policy
                </a>
                <a href="#" className="basis-auto">
                  Manage Cookies
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
