/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HeaderProps {
  title: string;
  subtitle: string;
}

const Header: React.FC<HeaderProps> = ({ title, subtitle }) => {
  return (
    <header className="flex flex-col items-center px-6 md:px-10  w-full bg-white  ">
      <div className="flex flex-col overflow-hidden items-center py-20 gap-10 text-center bg-sky-900 ">
        <p className="md:text-6xl text-4xl font-bold text-white md:leading-[60px] md:w-[700px] ">
          {title}
        </p>
        <div className="text-xl md:text-2xl leading-8 text-slate-300 w-[100vw] px-4 ">
          {subtitle}
        </div>
      <button className="flex z-10 gap-2 items-start pt-2.5 pr-5 pb-3.5 pl-7 mt-0 text-lg leading-none text-center text-white bg-blue-500 rounded-xl border border-blue-500 border-solid max-md:pl-5">
        <span>Get Started</span>
        <span className="whitespace-nowrap">→</span>
      </button>
      </div>
    </header>
  );
};

export default Header;
