/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import ServiceCard from "./ServiceCard";
import ClientLogo from "./ClientLogo";
import TestimonialCard from "./TestimonialCard";
import BlogCard from "./BlogCard";
import Footer from "./Footer";

const HomePage: React.FC = () => {
  const services = [
    {
      title: "QR Management Solutions",
      description:
        "Streamline your payment processes with our robust QR code solutions designed for easy integration and maximum efficiency.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/cda51807e6ee5f8767e14fb21088c56d5b0fd3aaa8425036ef5ec1b7fe900214?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
    {
      title: "Soundbox Management Solutions",
      description:
        "Enhance customer engagement with our advanced soundbox solutions, offering seamless integration, quality checks, and comprehensive management.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f75b4525060b30af8259787be89ac3dc49cff1302fb1b1dd1f600229e015ad8d?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
    {
      title: "Merchant Management Solutions",
      description:
        "From technology stacks to merchant acquisition, our solutions simplify and optimize your merchant management processes.",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/7320d8db24a8785d8c05f48a572076d9efbd3a35a79b3e65aad9533e2ebeccf1?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
  ];

  const clients = [
    {
      name: "Client1",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/273954850fd59045fba0b1f6342300c3b30a55f27fe37042174de71a92cd785f?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
    {
      name: "Client2",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/12bdf077fd5beb2270a08263df83442b882580ee7d8d7a729b71018642b5af6b?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
    {
      name: "Client3",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/36b3e19a26b297678d0e29636503e262589fbcffcc80fd2011ddcfd9a7724164?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
    {
      name: "Client4",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/de85c13bda2db43b2112909634a572c9a8366c837fbe9e8f4465e3e242b2e282?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
  ];

  const testimonials = [
    {
      heading: "Heading of Quote",
      quote:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    },
    {
      heading: "Heading of Quote",
      quote:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    },
    {
      heading: "Heading of Quote",
      quote:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation",
    },
  ];

  const blogPosts = [
    {
      type: "Type",
      heading: "Heading of the news/blog",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/d19a43ce5eea00bc96124d37a072b613c9e5aa8d1f28cd1b196218ebd4e58581?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
    {
      type: "Type",
      heading: "Heading of the news/blog",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/d19a43ce5eea00bc96124d37a072b613c9e5aa8d1f28cd1b196218ebd4e58581?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
    {
      type: "Type",
      heading: "Heading of the news/blog",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/d19a43ce5eea00bc96124d37a072b613c9e5aa8d1f28cd1b196218ebd4e58581?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
    },
  ];

  return (
    <div className="flex flex-col items- w-[100vw] ">
      <Header 
        title="One-stop solution for comprehensive business services"
        subtitle="Welcome to Brandigo, your one-stop solution for comprehensive business services designed to elevate your brand and streamline your operations. With a diverse portfolio of offerings ranging from QR Management Solutions and Soundbox Management to Merchant Management, Printing Solutions, and Digital Marketing, Brandigo is dedicated to empowering businesses with cutting-edge technology and innovative strategies. Our commitment to excellence and customer satisfaction has positioned us as a trusted partner for numerous esteemed clients across various industries."
      />

      <section className="w-full">
        <h2 className="mt-32 text-6xl font-extrabold tracking-tighter leading-none text-center text-black max-md:mt-10 max-md:text-4xl">
          Our Services
        </h2>
        <div className="flex flex-wrap justify-center items-center gap-4 mt-16 w-full font-extrabold text-black max-md:mt-10 ">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3210fd227f953af586b2592c4dd660ea082c9adbaf82693579a74db338196ea3?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-12 aspect-square"
          />
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 items-center ">
            {services.map((service, index) => (
              <ServiceCard key={index} {...service} />
            ))}
          </div>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/24f79c34bb642d3374772921a30f0f296a6d057f6fc5c132caf4c724d497cf92?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-12 aspect-square"
          />
        </div>
      </section>

      <section className="w-full">
        <h2 className="mt-32 text-6xl font-extrabold tracking-tighter leading-none text-center text-black ">
          Our Clients
        </h2>
        <div className="flex overflow-hidden items-center justify-center self-start py-20 bg-white w-full">
          <div className="px-8 pt-5  ">
            <div className="flex gap-5 max-md:flex-col">
              {clients.map((client, index) => (
                <ClientLogo key={index} {...client} />
              ))}
            </div>
          </div>
        </div>
        <div className="flex justify-center items-center">
        <button className="flex z-10 gap-2 items-center py-4 px-10 justify-center text-lg leading-none text-center text-white bg-blue-500 rounded-xl border border-blue-500 ">
          <span>More About Our Clients</span>
          <span className="whitespace-nowrap">→</span>
        </button>
        </div>
      </section>

      <section className="flex flex-col items-center w-full justify-center mt-10">
        <h2 className="px-16 pt-20 pb-10 max-w-full text-6xl font-extrabold tracking-tighter leading-none text-center whitespace-nowrap text-slate-900 w-[1120px] max-md:px-5 max-md:text-4xl">
          Testimonials
        </h2>
        <div className="flex flex-wrap gap-5 items-start px-2.5 mt-10 max-md:max-w-full">
          {testimonials.map((testimonial, index) => (
            <TestimonialCard key={index} {...testimonial} />
          ))}
        </div>
      </section>

      <section className="w-full">
        <h2 className="overflow-hidden flex justify-center items-center  mt-20 text-6xl font-extrabold tracking-tighter leading-none text-center text-slate-900 ">
          Latest News/Blogs
        </h2>
        <div className=" items-center mt-28 w-full max-md:mt-10 gap-10">
          <div className="w-full flex justify-center items-center gap-10">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-20 max-md:flex-col">
              {blogPosts.map((post, index) => (
                <BlogCard key={index} {...post} />
              ))}
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default HomePage;
