/**
 * This code was generated by Builder.io.
 */
import React from "react";

const NewServiceCard = ({
  title,
  description,
  features,
  benefits,
  imageSrc,
  isReversed,
}) => {
  const contentOrder = isReversed ? "order-2" : "order-1";
  const imageOrder = isReversed ? "order-1" : "order-2";

  return (
    <div
      className={`flex flex-col items-center mt-20 w-full max-md:mt-10 max-md:max-w-full ${
        isReversed ? "bg-sky-900 text-white" : ""
      }`}
    >
      <div className="z-10 w-full max-w-[1212px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div
            className={`flex flex-col w-6/12 max-md:ml-0 max-md:w-full ${imageOrder}`}
          >
            <img
              loading="lazy"
              src={imageSrc}
              alt={`${title} illustration`}
              className="object-contain w-full aspect-[1.72] max-md:mt-10 max-md:max-w-full"
            />
          </div>
          <div
            className={`flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full ${contentOrder}`}
          >
            <div className="flex flex-col mt-4 w-full max-md:mt-10 max-md:max-w-full">
              <h3 className="text-4xl font-semibold leading-10">{title}</h3>
              <p className="mt-12 text-xl font-medium leading-7 max-md:mt-10 max-md:max-w-full">
                {description}
              </p>
              <div className="mt-8">
                <h4 className="font-bold">Features</h4>
                <ul className="list-disc pl-5 mt-2">
                  {features.map((feature, index) => (
                    <li key={index} className="text-xl leading-8">
                      {feature}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="mt-8">
                <h4 className="font-bold">Benefits</h4>
                <ul className="list-disc pl-5 mt-2">
                  {benefits.map((benefit, index) => (
                    <li key={index} className="text-xl leading-8">
                      {benefit}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default NewServiceCard;

