/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceSection from "./ServiceSection";
import Header from "./Header/Header";

const ServicesPage = () => {
  return (
    <div className="flex flex-col">
      {/* <Header /> */}
      <Header/>
      <main>
        <ServiceSection />
      </main>
    </div>
  );
};

export default ServicesPage;
