/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ServiceCardProps {
  title: string;
  description: string;
  imageSrc: string;
}

const ServiceCard: React.FC<ServiceCardProps> = ({
  title,
  description,
  imageSrc,
}) => {
  return (
    <div className="flex overflow-hidden flex-col pt-11 rounded-2xl border-4 border-blue-700 border-solid min-w-[240px] w-[403px]">
      <div className="flex flex-col px-7 w-full max-md:px-5">
        <h3 className="ml-2.5 text-2xl tracking-tighter leading-none max-md:mr-2.5">
          {title}
        </h3>
        <p className="mt-12 text-base leading-6 max-md:mt-10">{description}</p>
        <div className="flex gap-2 items-center self-start mt-9 text-sm leading-none uppercase tracking-[3px]">
          <span className="self-stretch my-auto">see more</span>
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/f8d9a3ebd1d20fbb6f6b24a74b94daba7002b97ce7c0aa71048931c17f5796e7?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
            alt=""
            className="object-contain shrink-0 self-stretch my-auto w-3.5 aspect-square"
          />
        </div>
      </div>
      <img
        loading="lazy"
        src={imageSrc}
        alt={title}
        className="object-contain mt-6 w-full aspect-[1.89] max-md:mr-1"
      />
    </div>
  );
};

export default ServiceCard;
