/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TestimonialCardProps {
  heading: string;
  quote: string;
}

const TestimonialCard: React.FC<TestimonialCardProps> = ({
  heading,
  quote,
}) => {
  return (
    <div className="flex flex-col pt-6 pr-6 pb-11 pl-6 min-w-[240px] w-[360px] max-md:px-5">
      <h3 className="text-2xl font-bold tracking-tight leading-none text-slate-900">
        {heading}
      </h3>
      <p className="mt-7 text-lg leading-6 text-slate-900 text-opacity-60">
        {quote}
      </p>
    </div>
  );
};

export default TestimonialCard;
