/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Button = ({ label }) => (
  <button className="self-stretch py-4 px-6 leading-none text-white bg-blue-500 rounded-3xl border border-blue-500 border-solid max-md:px-5">
    {label}
  </button>
);

export default Button;
