/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CaseStudy = ({ title, image, challenge, solution, outcome }) => (
  <article className="mt-32 max-md:mt-10">
    <img
      loading="lazy"
      src={image}
      alt={title}
      className="object-contain w-full max-w-screen-lg aspect-[3.09] max-md:max-w-full"
    />
    <h3 className="mt-6 font-bold leading-none text-center">{title}</h3>
    <div className="mt-9 mr-14 max-md:mr-2.5 max-md:max-w-full">
      <p>
        <strong>Challenge:</strong> {challenge}
      </p>
      <br />
      <p>
        <strong>Solution:</strong> {solution}
      </p>
      <br />
      <p>
        <strong>Outcome:</strong> {outcome}
      </p>
    </div>
  </article>
);

export default CaseStudy;
