/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CaseStudy from "./CaseStudy";

const CaseStudySection = () => {
  const caseStudies = [
    {
      title: "Razorpay: QR Printing Solution",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/2d237012864bb8bcd2e30ecb03b939853b1ea1b7cb430f4c8d3a8587a808bbe9?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      challenge:
        "Razorpay needed a reliable partner to handle the high-volume printing of QR codes for their merchants.",
      solution:
        "Brandigo provided a comprehensive QR Management Solution that included QR code generation, quality assurance, and delivery.",
      outcome:
        "We successfully delivered over 100,000 QR codes, ensuring timely and accurate distribution, which helped Razorpay enhance their merchant services and streamline transactions.",
    },
    {
      title: "Fiserv: Soundbox Management",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/e7befbf4c812f5288d1ccce76b3791c7fe637f9e7579d1e2d447f0219eb7a7f0?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      challenge:
        "Fiserv required a robust solution for managing soundboxes across multiple merchant locations.",
      solution:
        "Brandigo implemented a Soundbox Management Solution that included procurement, integration, quality checks, and distribution.",
      outcome:
        "The solution improved operational efficiency and customer satisfaction, leading to a significant increase in merchant engagement and transaction volumes.",
    },
    {
      title: "Yes Bank: Merchant Management System",
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/fc6471ad6f22a60688c4b53eea8ae95ef3e1a6cce63de36595f766eafe484dfe?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      challenge:
        "Yes Bank needed a comprehensive system to manage their growing number of merchants and streamline onboarding processes.",
      solution:
        "Brandigo developed a Merchant Management Solution that included a technology stack for onboarding, QR code management, and soundbox solutions.",
      outcome:
        "The implementation of our system resulted in faster onboarding times, better merchant support, and increased overall efficiency for Yes Bank.",
    },
  ];

  return (
    <section className="flex flex-col self-center mt-40 mb-0 w-full text-2xl leading-8 text-black max-w-[1068px] max-md:mt-10 max-md:mb-2.5 max-md:max-w-full">
      <h2 className="self-center mt-60 ml-4 text-6xl font-medium leading-none text-center max-md:mt-10 max-md:text-4xl">
        Case Study
      </h2>
      <p className="self-center mt-36 text-center max-md:mt-10 max-md:max-w-full">
        At Brandigo, we believe in showcasing our success stories to demonstrate
        the impact of our solutions. Our case studies provide detailed insights
        into how we have helped our clients achieve their goals, overcome
        challenges, and drive growth.
        <br />
        <br />
        Here are some examples of our successful projects:
      </p>
      {caseStudies.map((study, index) => (
        <CaseStudy key={index} {...study} />
      ))}
    </section>
  );
};

export default CaseStudySection;
