/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ClientSection = () => (
  <section className="flex flex-col items-center mt-24 max-md:mt-10">
    <h2 className="text-2xl leading-8 text-center text-black max-w-[1068px] max-md:max-w-full">
      Our clients are at the heart of everything we do. We partner with a wide
      range of businesses, from large enterprises to growing startups, across
      multiple sectors including finance, retail, healthcare, and technology.
    </h2>
    <h3 className="mt-24 text-2xl font-semibold leading-8 text-center text-black max-md:mt-10 max-md:max-w-full">
      Here are some of the esteemed clients we have had the privilege of working
      with
    </h3>
  </section>
);

export default ClientSection;
