/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ClientLogos = () => {
  const logos = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/03d8ec15eee925e8d64a16c9336639ef66707465dff60debce068dba2631bdc6?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      alt: "Client Logo 1",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/d0e597491d85c18398ec47b34114186ac717d9c5b1b0c10be996949ccbe1c0b9?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      alt: "Client Logo 2",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/0c86c32563cb83bf12b9548eba8d726e3aae54f3f31355759a1c587f995feca9?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      alt: "Client Logo 3",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/e1fdb06cd1a2bdd613ccc8eb29bba9048b6492a8da309044f91ec1b0512a6889?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      alt: "Client Logo 4",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/bd2508e951718a5de58c573def2ccf518b9772c4fa6e39bc49bacddd1db6e6ef?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      alt: "Client Logo 5",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/049a62ec0ab19b72d307ed27da77b8ba5ee1c465c6a30238a898da1d9854eff8?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      alt: "Client Logo 6",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/71f756a071301c39d2db2cff92464298e501e06225ec113e0ea1afe7d59720e7?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      alt: "Client Logo 7",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/12a3a4db1c47d36d4cda1f83ede30fc049ad674e120f2fba741f360231b33153?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      alt: "Client Logo 8",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/df07762fbe0018a5afbeac4b0085c1f6c4fc2b73bccdc3d618407ad655cd6db8?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196",
      alt: "Client Logo 9",
    },
  ];

  return (
    <div className="flex flex-col items-end px-20 py-16 mt-20 w-full bg-zinc-300 max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="self-center ml-6 w-full max-w-[1138px] max-md:max-w-full">
        <div className="flex flex-wrap gap-5 justify-between">
          {logos.map((logo, index) => (
            <img
              key={index}
              loading="lazy"
              src={logo.src}
              alt={logo.alt}
              className="object-contain max-w-full aspect-[2.43] w-[221px] max-md:mt-10"
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default ClientLogos;
