/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroSection = () => (
  <section className="flex relative flex-col items-center px-20 mt-10 w-full min-h-[598px] max-md:px-5 max-md:mt-10 max-md:max-w-full">
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/d2ac308c5d5432146909bfc69bd62d6b2ffb6a75996073381b2e10b0bb94068d?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
      alt="Background"
      className="object-cover absolute inset-0 size-full"
    />
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/aa078fca097f8dc8b74475677aac620653eb5dcea7c23e9a0500f1960b0a6a51?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
      alt="Hero Content"
      className="object-contain w-full aspect-[1.9] max-w-[1136px] max-md:max-w-full"
    />
  </section>
);

export default HeroSection;
