/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import HeroSection from "./HeroSection";
import ClientSection from "./ClientSection";
import ClientLogos from "./ClientLogos";
import CaseStudySection from "./CaseStudySection";

function MainComponent() {
  return (
    <main className="flex flex-col">
      <div className="flex flex-col pb-32 w-full bg-white max-md:pb-24 max-md:max-w-full">
        <Header />
        <HeroSection />
        <ClientSection />
        <ClientLogos />
        <CaseStudySection />
      </div>
    </main>
  );
}

export default MainComponent;
