/**
 * This code was generated by Builder.io.
 */
import React from "react";

const NavItem = ({ label, hasDropdown }) => (
  <div className="flex gap-0.5 self-stretch my-auto text-center">
    <div className="grow">{label}</div>
    {hasDropdown && (
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/b632bf11099d01cc005c85cbcadb103d172f347dcc0d5f0aca9e93161e5d75f4?placeholderIfAbsent=true&apiKey=0d7a153a28b9484c96314809a6915196"
        alt=""
        className="object-contain shrink-0 self-start mt-2.5 w-3 aspect-[1.2]"
      />
    )}
  </div>
);

export default NavItem;
